# Generated by Django 4.0.1 on 2022-02-04 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_posts_picture'),
        ('camera', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='user',
        ),
        migrations.AddField(
            model_name='camera',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.posts'),
        ),
    ]
