# Generated by Django 4.0.1 on 2022-02-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_user_id_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
