# Generated by Django 4.0.1 on 2022-02-04 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_posts_options_alter_posts_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='picture',
        ),
    ]
