# Generated by Django 4.0.1 on 2022-02-04 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_posts_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='file',
        ),
    ]
