# Generated by Django 4.0.1 on 2022-02-04 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_files_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='user',
            new_name='post',
        ),
    ]
